
import { collection, doc, getDoc, getDocs, query, where, setDoc, updateDoc, onSnapshot, runTransaction, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const F=window.ExploraFirebase||{},db=F.db,auth=F.auth,$=id=>document.getElementById(id);
const COLLABORATION_RATE=.10;
const STATUS=Object.freeze({PENDING:"PENDIENTE",ACCEPTED:"ACEPTADA",REJECTED:"RECHAZADA",PENDING_INVOICE:"PENDIENTE_FACTURACION",INVOICED:"FACTURADA",CLOSED_REJECTED:"CERRADA_RECHAZADA"});
const state={drivers:[],driverMap:new Map(),selectedReceiverUid:"",pendingResponse:[],pendingCompletion:[],allReceived:[],activeTab:"received",renderSignature:"",selectedFinalizeId:"",selectedPayment:"",busy:new Set(),unsubscribe:null,originalBillingAction:null,opened:false,previousScrollY:0};
let derivationSaveInProgress=false;
const normalize=value=>String(value||"").trim().toLowerCase();
const money=value=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(value)||0).replace(/\s/g,"");
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function parseCurrencyInput(value){const amount=Number(String(value||"").replace(/\$/g,"").replace(/\s/g,"").replace(/\./g,"").replace(/,/g,".").replace(/[^\d.-]/g,""));return Number.isFinite(amount)&&amount>0?Math.round(amount):0;}
function formatCurrencyInput(value){const digits=String(value||"").replace(/\D/g,"").replace(/^0+/,"");return digits?Number(digits).toLocaleString("es-AR"):"";}
const uid=()=>auth?.currentUser?.uid||"";
const currentPeriod=()=>window.ExploraPeriods?.getActivePeriods?.().weeklyPeriodId||window.ExploraWeeklyEngine?.getActiveWeeklyPeriod?.().id||"";
const stableId=()=>`drv_${uid().slice(0,10)}_${Date.now()}_${globalThis.crypto?.randomUUID?.().slice(0,8)||Math.random().toString(36).slice(2,10)}`.replace(/[^a-zA-Z0-9_-]/g,"").slice(0,100);
const getAvatar=profile=>window.resolveProfileAvatar?.(profile)||profile?.avatarUrl||profile?.fotoPerfil||profile?.photoURL||profile?.avatar||profile?.foto||"";
const getName=profile=>String(profile?.nombre||profile?.nombreCompleto||profile?.displayName||profile?.usuario||"Chofer").trim();
const getVehicle=profile=>String(profile?.vehicleDisplay||profile?.vehiculoNombre||profile?.vehiculo||"Vehículo no asignado");
function canonicalStatus(row={}){const raw=normalize(row.status||row.estado||row.estadoDerivacion);if(["pendiente","sent_pending_response"].includes(raw))return STATUS.PENDING;if(["aceptada","accepted"].includes(raw))return STATUS.ACCEPTED;if(["pendiente_facturacion","accepted_pending_completion"].includes(raw))return STATUS.PENDING_INVOICE;if(["facturada","completed","completada"].includes(raw))return STATUS.INVOICED;if(["rechazada","rejected"].includes(raw))return STATUS.REJECTED;if(["cerrada_rechazada","canceled","cancelada"].includes(raw))return STATUS.CLOSED_REJECTED;return String(row.status||row.estado||"").toUpperCase();}
function setMessage(text="",type=""){const element=$("derivationFormMessage");if(element){element.textContent=text;element.className=`derivation-message${type?` ${type}`:""}`;}}
async function ensureSession(){const user=auth?.currentUser;if(!user?.uid)throw Object.assign(new Error("Sesión Firebase inexistente."),{code:"AUTH_REQUIRED"});return user;}
function reportDerivationError(stage,code,error,context={}){const payload={stage,code,error,context:{...context,module:"DERIVATION_MONEY_RANKING",functionName:context.functionName||"ExploraDerivations",derivationState:context.derivationState||context.status||"—",emisorUid:context.emisorUid||context.senderUid||uid()||"—",receptorUid:context.receptorUid||context.receiverUid||state.selectedReceiverUid||"—",derivationId:context.derivationId||"—",weeklyPeriodId:context.weeklyPeriodId||currentPeriod()||"—",firestorePath:context.firestorePath||"derivaciones",firestoreConfirmed:Boolean(context.firestoreConfirmed),suggestedAmount:Number(context.suggestedAmount||0),finalAmount:Number(context.finalAmount||0),paymentMethod:context.paymentMethod||"—",derivedAmount:Number(context.derivedAmount||0),collaborationAmount:Number(context.collaborationAmount||0),leaderBonus:Number(context.leaderBonus||0)}};if(typeof window.ExploraPerformanceEngine?.showDiagnostic==="function")window.ExploraPerformanceEngine.showDiagnostic(stage,code,error,payload.context);else window.__exploraPendingGoalDiagnostic=payload;}

async function loadDrivers(force=false){
  try{
    await ensureSession();if(state.drivers.length&&!force)return state.drivers;
    const snapshot=await getDocs(query(collection(db,"choferes"),where("activo","==",true)));
    state.drivers=snapshot.docs.map(item=>({id:item.id,...item.data()})).filter(profile=>!normalize(profile.role||profile.rol||"driver").includes("admin")&&String(profile.uid||profile.authUid||profile.id)!==uid());
    state.driverMap=new Map(state.drivers.map(profile=>[String(profile.uid||profile.authUid||profile.id),profile]));return state.drivers;
  }catch(error){reportDerivationError("INIT","DRIVER_LIST_READ_FAILED",error,{functionName:"loadDrivers",firestorePath:"choferes"});throw error;}
}
function renderDrivers(){const box=$("derivationDriverGrid");if(!box)return;box.innerHTML=state.drivers.map(profile=>{const id=String(profile.uid||profile.authUid||profile.id),selected=id===state.selectedReceiverUid,avatar=getAvatar(profile);return`<button type="button" class="derivation-driver-card${selected?" is-selected":""}" data-select-derivation-driver="${escapeHtml(id)}"><span class="derivation-avatar">${avatar?`<img src="${escapeHtml(avatar)}" alt="">`:escapeHtml(getName(profile).slice(0,2).toUpperCase())}</span><span class="derivation-card-copy"><strong>${escapeHtml(getName(profile))}</strong><small>Chofer EXPLORA</small></span><i>${selected?"✓":""}</i></button>`;}).join("")||'<p class="derivation-empty">No hay choferes disponibles.</p>';}
function updateCompose(){const concept=String($("derivationDescription")?.value||"").trim(),amount=parseCurrencyInput($("derivationAmount")?.value),receiver=state.driverMap.get(state.selectedReceiverUid);$("derivationSummaryReceiver")&&($("derivationSummaryReceiver").textContent=receiver?getName(receiver):"Sin seleccionar");$("derivationSummaryService")&&($("derivationSummaryService").textContent=concept||"Sin completar");$("derivationSummaryPrice")&&($("derivationSummaryPrice").textContent=money(amount));const button=$("derivationSendBtn");if(button)button.disabled=derivationSaveInProgress||!(state.selectedReceiverUid&&concept&&amount>0&&state.selectedReceiverUid!==uid());}
function resetForm(){state.selectedReceiverUid="";$("derivationDescription")&&($("derivationDescription").value="");$("derivationAmount")&&($("derivationAmount").value="");setMessage("");renderDrivers();updateCompose();}
async function sendDerivation(event){
  event.preventDefault();if(derivationSaveInProgress)return;const button=$("derivationSendBtn");let runtime={functionName:"sendDerivation",derivationState:STATUS.PENDING,receiverUid:state.selectedReceiverUid,suggestedAmount:parseCurrencyInput($("derivationAmount")?.value),weeklyPeriodId:currentPeriod()};
  try{
    const user=await ensureSession(),receiverUid=String(state.selectedReceiverUid||"").trim(),concept=String($("derivationDescription")?.value||"").trim(),suggestedAmount=parseCurrencyInput($("derivationAmount")?.value);
    runtime={...runtime,emisorUid:user.uid,receptorUid:receiverUid,suggestedAmount};
    if(!receiverUid)throw Object.assign(new Error("Selecciona un chofer receptor."),{code:"RECEIVER_REQUIRED"});
    if(receiverUid===user.uid)throw Object.assign(new Error("El receptor debe ser distinto del emisor."),{code:"SAME_DRIVER_NOT_ALLOWED"});
    if(!concept)throw Object.assign(new Error("El concepto es obligatorio."),{code:"CONCEPT_REQUIRED"});
    if(!(suggestedAmount>0))throw Object.assign(new Error("El monto debe ser mayor a cero."),{code:"AMOUNT_REQUIRED"});
    const receiver=state.driverMap.get(receiverUid);if(!receiver)throw Object.assign(new Error("UID receptor inválido."),{code:"RECEIVER_UID_INVALID"});
    derivationSaveInProgress=true;button.disabled=true;button.textContent="ENVIANDO…";button.setAttribute("aria-busy","true");
    const id=stableId(),sender=window.ExploraSession?.profile||{},period=currentPeriod();
    await setDoc(doc(db,"derivaciones",id),{derivationId:id,weeklyPeriodId:period,emisorUid:user.uid,emisorName:getName(sender),emisorPhotoUrl:getAvatar(sender),receptorUid:receiverUid,receptorName:getName(receiver),receptorPhotoUrl:getAvatar(receiver),senderUid:user.uid,senderName:getName(sender),senderPhotoUrl:getAvatar(sender),receiverUid,receiverName:getName(receiver),receiverPhotoUrl:getAvatar(receiver),concept,description:concept,descripcion:concept,suggestedAmount,amount:suggestedAmount,monto:suggestedAmount,finalAmount:0,paymentMethod:null,status:STATUS.PENDING,estado:STATUS.PENDING,collaborationRate:COLLABORATION_RATE,collaborationAmount:0,derivedAmountForEmitter:0,createdByUid:user.uid,createdAt:serverTimestamp(),sentAt:serverTimestamp(),acceptedAt:null,rejectedAt:null,invoicedAt:null,updatedAt:serverTimestamp()},{merge:false});
    runtime={...runtime,derivationId:id,firestoreConfirmed:true,firestorePath:`derivaciones/${id}`};
    window.showExploraSuccess?.({title:"DERIVACIÓN EXITOSA",message:"Derivación enviada correctamente.",onAccept:()=>{resetForm();setDerivationTab("received");loadPendingCompletion().catch(()=>{});$("derivationScreen")?.scrollTo?.({top:0,behavior:"smooth"});}});
  }catch(error){const code=String(error?.code||error?.message||"DERIVATION_CREATE_FAILED");reportDerivationError(code.includes("REQUIRED")||code.includes("INVALID")||code.includes("SAME_")?"VALIDATE_DERIVATION_FORM":"CREATE_DERIVATION",code,error,runtime);setMessage(error?.message||"No se pudo enviar la derivación.","err");}
  finally{derivationSaveInProgress=false;if(button){button.disabled=false;button.textContent="ENVIAR";button.removeAttribute("aria-busy");}updateCompose();}
}
function notificationAvatar(row){const photo=String(row.emisorPhotoUrl||row.senderPhotoUrl||"").trim(),name=String(row.emisorName||row.senderName||"Chofer");return photo?`<span class="derivation-notification-photo"><img src="${escapeHtml(photo)}" alt="Foto de ${escapeHtml(name)}"></span>`:`<span class="derivation-notification-photo">${escapeHtml(name.slice(0,2).toUpperCase())}</span>`;}
function syncPendingDerivationButton(){const pulsingStatuses=new Set([STATUS.PENDING,STATUS.ACCEPTED,STATUS.PENDING_INVOICE]);const active=[...state.pendingResponse,...state.pendingCompletion].some(row=>pulsingStatuses.has(canonicalStatus(row)));document.querySelectorAll('[data-action="derivar-servicio"]').forEach(button=>{button.classList.toggle("has-pending-derivation",active);button.setAttribute("aria-live","polite");button.setAttribute("aria-label",active?"Derivar servicio. Hay una derivación pendiente de respuesta o facturación.":"Derivar servicio");});}
function removeLegacyDerivationCounters(){document.querySelectorAll("#derivationNotificationBadge,.derivation-notification-badge,.derivation-counter-badge,[data-derivation-counter]").forEach(node=>node.remove());}
function derivationTimestamp(row={}){const value=row.serviceDate||row.fechaServicio||row.createdAt||row.sentAt||row.updatedAt;try{return value?.toMillis?.()||value?.seconds*1000||new Date(value||0).getTime()||0;}catch(_){return 0;}}
function getDerivationOperationalState(row={}){const status=canonicalStatus(row),method=String(row.paymentMethod||row.metodoPago||"").trim(),finalAmount=Number(row.finalAmount||row.montoFinal||0),isFinalized=status===STATUS.INVOICED,isRejected=[STATUS.REJECTED,STATUS.CLOSED_REJECTED].includes(status);let code="REVIEW_REQUIRED",label="REVISAR",detail="Revisá la información de esta derivación.",priority=60,section="pending",primaryAction="";if(status===STATUS.PENDING){code="RECEIVED_PENDING_ACCEPTANCE";label="NUEVA";detail="Aceptá o rechazá esta derivación.";priority=50;primaryAction="accept";}else if([STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(status)&&!(finalAmount>0)){code="PENDING_COMPLETION";label="PENDIENTE DE CARGA";detail="Ingresá el monto final y seleccioná el medio de pago.";priority=10;primaryAction="complete";}else if([STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(status)&&!method){code="PENDING_PAYMENT_METHOD";label="FALTA MEDIO DE PAGO";detail="Seleccioná un medio de pago para completar la derivación.";priority=20;primaryAction="complete";}else if([STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(status)){code="PENDING_BILLING";label="PENDIENTE DE FACTURACIÓN";detail="Registrá el cobro para finalizar.";priority=30;primaryAction="complete";}else if(isFinalized){code="COMPLETED";label="FINALIZADA";detail="Facturación registrada.";priority=100;section="finalized";}else if(isRejected){code=status===STATUS.REJECTED?"REJECTED":"CANCELLED";label=status===STATUS.REJECTED?"RECHAZADA":"CANCELADA";detail="La derivación fue cerrada.";priority=110;section="finalized";}return{code,label,detail,priority,section,primaryAction,canAccept:status===STATUS.PENDING,canComplete:[STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(status),canReject:![STATUS.INVOICED,STATUS.REJECTED,STATUS.CLOSED_REJECTED].includes(status),isActive:![STATUS.INVOICED,STATUS.REJECTED,STATUS.CLOSED_REJECTED].includes(status),isFinalized};}
function stableDerivationSort(a,b){const sa=getDerivationOperationalState(a),sb=getDerivationOperationalState(b);if(sa.priority!==sb.priority)return sa.priority-sb.priority;const ta=derivationTimestamp(a),tb=derivationTimestamp(b);if(sa.priority<=50&&ta!==tb)return ta-tb;if(ta!==tb)return tb-ta;return String(a.id||a.derivationId||"").localeCompare(String(b.id||b.derivationId||""));}
function isCurrentWeekDerivation(row){const period=currentPeriod(),rowPeriod=String(row.weeklyPeriodIdCompleted||row.weeklyPeriodId||row.periodoSemanalId||row.periodoId||"");return !rowPeriod||rowPeriod===period;}
function operationalCard(row,isCurrent=false){const st=getDerivationOperationalState(row),sender=row.emisorName||row.senderName||"Chofer",photo=row.emisorPhotoUrl||row.senderPhotoUrl||"",initials=String(sender).slice(0,2).toUpperCase(),amount=Number(row.finalAmount||row.suggestedAmount||row.amount||row.monto||0);let actions="";if(st.canAccept)actions=`<div class="derivation-operational-actions"><button class="accept" data-derivation-action="accept" data-derivation-id="${escapeHtml(row.id)}">ACEPTAR DERIVACIÓN</button><button class="danger" data-derivation-action="reject" data-derivation-id="${escapeHtml(row.id)}">RECHAZAR</button></div>`;else if(st.canComplete)actions=`<div class="derivation-operational-actions"><button class="danger" data-derivation-final-reject="${escapeHtml(row.id)}">RECHAZAR DEFINITIVAMENTE</button><button class="primary" data-reminder-finalize="${escapeHtml(row.id)}">COMPLETAR CARGA</button></div>`;return`<article class="derivation-operational-card${isCurrent?" is-current":""}"><div class="derivation-operational-head"><span class="derivation-avatar">${photo?`<img src="${escapeHtml(photo)}" alt="">`:escapeHtml(initials)}</span><span class="derivation-operational-copy"><strong>${escapeHtml(row.concept||row.description||row.descripcion||"Servicio")}</strong><small>Derivada por ${escapeHtml(sender)} · ${new Date(derivationTimestamp(row)||Date.now()).toLocaleString("es-AR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</small></span><span class="derivation-operational-amount">${money(amount)}</span></div><div class="derivation-operational-status"><span>${escapeHtml(st.label)}</span><small>${escapeHtml(st.detail)}</small></div>${actions}</article>`;}
function finalizedCard(row){const sender=row.emisorName||row.senderName||"Chofer",amount=Number(row.finalAmount||row.suggestedAmount||row.amount||0),method=String(row.paymentMethod||row.metodoPago||"—").toUpperCase(),collab=Number(row.collaborationAmount||0);return`<article class="derivation-final-card"><div class="derivation-final-card-head"><strong>${escapeHtml(row.concept||row.description||"Servicio")}</strong><b>${money(amount)}</b></div><small>Derivada por ${escapeHtml(sender)} · ${escapeHtml(method)}${collab?` · Colaboración ${money(collab)}`:""}</small><small>FINALIZADA · Facturación confirmada</small></article>`;}
function setDerivationTab(tab="received"){state.activeTab=tab==="create"?"create":"received";const screen=$("derivationScreen");if(screen)screen.dataset.derivationView=state.activeTab;document.querySelectorAll("[data-derivation-tab]").forEach(btn=>btn.classList.toggle("is-active",btn.dataset.derivationTab===state.activeTab));document.querySelectorAll("[data-derivation-panel]").forEach(panel=>panel.classList.toggle("is-active",panel.dataset.derivationPanel===state.activeTab));if(state.activeTab==="received")renderReceivedWorkflow();else{renderDrivers();updateCompose();}}
function renderReceivedWorkflow(){
  const byId=new Map();
  for(const raw of (state.allReceived||[])){
    const key=String(raw?.id||raw?.derivationId||"").trim();
    if(!key)continue;
    byId.set(key,{...raw,id:key});
  }
  const consolidated=[...byId.values()].sort(stableDerivationSort);
  const incoming=[],accepted=[],finalized=[];
  for(const row of consolidated){
    const status=canonicalStatus(row),op=getDerivationOperationalState(row);
    if(op.isFinalized){if(isCurrentWeekDerivation(row))finalized.push(row);continue;}
    if(status===STATUS.PENDING){incoming.push(row);continue;}
    if([STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(status)||op.isActive){accepted.push(row);}
  }
  const signature=JSON.stringify([...incoming,...accepted,...finalized].map(row=>[row.id,canonicalStatus(row),Number(row.finalAmount||0),row.paymentMethod||""]));
  if(signature===state.renderSignature)return;
  state.renderSignature=signature;
  const apply=(sectionId,rows,renderer)=>{const section=$(sectionId),list=$(sectionId.replace("Section","List"));if(section)section.hidden=!rows.length;if(list){const html=rows.map(renderer).join("");if(list.innerHTML!==html)list.innerHTML=html;}};
  apply("derivationCurrentSection",incoming,row=>operationalCard(row,true));
  apply("derivationPendingSection",accepted,row=>operationalCard(row,false));
  apply("derivationFinalizedSection",finalized,finalizedCard);
  $("derivationCurrentCount")&&($("derivationCurrentCount").textContent=String(incoming.length));
  $("derivationPendingCount")&&($("derivationPendingCount").textContent=String(accepted.length));
  $("derivationFinalizedCount")&&($("derivationFinalizedCount").textContent=String(finalized.length));
  $("derivationReceivedCount")&&($("derivationReceivedCount").textContent=String(incoming.length+accepted.length));
  const empty=$("derivationReceivedEmpty");if(empty)empty.hidden=Boolean(incoming.length||accepted.length||finalized.length);
  syncPendingDerivationButton();
}
function renderPendingNotifications(){removeLegacyDerivationCounters();const box=$("derivationNotificationStack");if(!box)return;box.hidden=!state.pendingResponse.length;box.innerHTML=state.pendingResponse.map(row=>`<article class="derivation-notification-card"><div class="derivation-notification-head">${notificationAvatar(row)}<span class="derivation-notification-copy"><strong>NUEVA DERIVACIÓN RECIBIDA</strong><b>${escapeHtml(row.emisorName||row.senderName||"Chofer")}</b><small>${escapeHtml(row.concept||row.description||row.descripcion||"Servicio")} · ${money(row.suggestedAmount||row.amount||row.monto)}</small></span></div><div class="derivation-notification-actions"><button class="accept" data-derivation-action="accept" data-derivation-id="${escapeHtml(row.id)}">ACEPTAR</button><button data-derivation-action="reject" data-derivation-id="${escapeHtml(row.id)}">RECHAZAR</button></div></article>`).join("");syncPendingDerivationButton();}
function pendingCard(row){const sender=row.emisorName||row.senderName||"Chofer",photo=row.emisorPhotoUrl||row.senderPhotoUrl||"",initials=String(sender).slice(0,2).toUpperCase();return`<article class="derivation-pending-card"><div class="derivation-pending-card-head"><span class="derivation-avatar">${photo?`<img src="${escapeHtml(photo)}" alt="">`:escapeHtml(initials)}</span><span><strong>${escapeHtml(row.concept||row.description||"Servicio")}</strong><small>Derivada por ${escapeHtml(sender)}</small></span><span class="derivation-pending-card-amount">${money(row.suggestedAmount||row.amount||0)}</span></div><div class="derivation-pending-card-actions"><button class="danger" data-derivation-final-reject="${escapeHtml(row.id)}">RECHAZAR DEFINITIVAMENTE</button><button class="primary" data-reminder-finalize="${escapeHtml(row.id)}">COMPLETAR CARGA</button></div></article>`;}
function startPendingListener(){try{state.unsubscribe?.();}catch(_){}if(!uid())return;const q=query(collection(db,"derivaciones"),where("receptorUid","==",uid()));state.unsubscribe=onSnapshot(q,snapshot=>{const rows=snapshot.docs.map(item=>({id:item.id,...item.data()}));state.allReceived=Array.from(new Map(rows.map(row=>[String(row.id||row.derivationId),row])).values());state.pendingResponse=state.allReceived.filter(row=>canonicalStatus(row)===STATUS.PENDING);state.pendingCompletion=state.allReceived.filter(row=>[STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(canonicalStatus(row)));renderPendingNotifications();renderReceivedWorkflow();},error=>reportDerivationError("READ_INCOMING_DERIVATIONS","DERIVATION_LISTENER_FAILED",error,{functionName:"startPendingListener",receptorUid:uid(),firestorePath:"derivaciones"}));}
async function loadPendingCompletion(){await ensureSession();const snapshot=await getDocs(query(collection(db,"derivaciones"),where("receptorUid","==",uid())));const rows=snapshot.docs.map(item=>({id:item.id,...item.data()}));state.allReceived=Array.from(new Map(rows.map(row=>[String(row.id||row.derivationId),row])).values());state.pendingResponse=state.allReceived.filter(row=>canonicalStatus(row)===STATUS.PENDING);state.pendingCompletion=state.allReceived.filter(row=>[STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(canonicalStatus(row)));renderReceivedWorkflow();return state.pendingCompletion;}
async function transition(id,action,button){if(state.busy.has(id))return;state.busy.add(id);const accept=action==="accept",stage=accept?"ACCEPT_DERIVATION":"REJECT_DERIVATION",idle=accept?"ACEPTAR":"RECHAZAR";button.disabled=true;button.textContent=accept?"ACEPTANDO…":"RECHAZANDO…";try{const me=await ensureSession(),reference=doc(db,"derivaciones",id);await runTransaction(db,async tx=>{const snapshot=await tx.get(reference);if(!snapshot.exists())throw Object.assign(new Error("La derivación ya no existe."),{code:"DERIVATION_NOT_FOUND"});const row=snapshot.data();if(String(row.receptorUid||row.receiverUid)!==me.uid||canonicalStatus(row)!==STATUS.PENDING)throw Object.assign(new Error("La derivación cambió de estado."),{code:"TRANSITION_DENIED"});tx.update(reference,accept?{status:STATUS.PENDING_INVOICE,estado:STATUS.ACCEPTED,acceptedAt:serverTimestamp(),acceptedByUid:me.uid,updatedAt:serverTimestamp()}:{status:STATUS.REJECTED,estado:STATUS.REJECTED,rejectedAt:serverTimestamp(),rejectedByUid:me.uid,updatedAt:serverTimestamp()});});window.ExploraWeeklyEngine?.invalidate?.(accept?"derivation-accepted":"derivation-rejected",{refresh:true});await loadPendingCompletion();window.showExploraSuccess?.({title:accept?"DERIVACIÓN ACEPTADA":"DERIVACIÓN RECHAZADA",message:accept?"Quedó pendiente de carga en el menú Derivaciones.":"La derivación se cerró sin beneficios."});}catch(error){reportDerivationError(stage,"DERIVATION_TRANSITION_FAILED",error,{functionName:"transition",derivationId:id,status:accept?STATUS.ACCEPTED:STATUS.REJECTED,receptorUid:uid()});}finally{state.busy.delete(id);button.disabled=false;button.textContent=idle;}}
function openFinalize(id){const row=state.pendingCompletion.find(item=>item.id===id);if(!row)return;state.selectedFinalizeId=id;state.selectedPayment="";const suggested=Math.round(Number(row.suggestedAmount||row.amount||row.monto||0));$("derivationFinalizeSummary").innerHTML=`<div><span>Concepto</span><strong>${escapeHtml(row.concept||row.description||"Servicio")}</strong></div><div><span>Monto sugerido</span><strong>${money(suggested)}</strong></div><div><span>Emisor</span><strong>${escapeHtml(row.emisorName||row.senderName||"Chofer")}</strong></div>`;$("derivationFinalAmount").value=formatCurrencyInput(suggested);document.querySelectorAll("[data-derivation-payment]").forEach(item=>item.classList.remove("is-selected"));$("derivationFinalizeConfirmBtn").disabled=false;$("derivationFinalizeConfirmBtn").setAttribute("aria-disabled","true");$("derivationFinalizeMessage").textContent="Seleccioná el medio de pago para completar la derivación.";$("derivationFinalizeMessage").classList.add("derivation-payment-required");$("derivationFinalizeBackdrop").classList.add("is-open");$("derivationFinalizeBackdrop").setAttribute("aria-hidden","false");window.lockPageScroll?.("derivation-finalize");}
function closeFinalize(){$("derivationFinalizeBackdrop")?.classList.remove("is-open");$("derivationFinalizeBackdrop")?.setAttribute("aria-hidden","true");window.unlockPageScroll?.("derivation-finalize");state.selectedFinalizeId="";state.selectedPayment="";}
function updateFinalizeButton(){
  const amount=parseCurrencyInput($("derivationFinalAmount")?.value),button=$("derivationFinalizeConfirmBtn"),message=$("derivationFinalizeMessage"),validPayment=["cash","transfer","card","other"].includes(state.selectedPayment);
  if(button){button.disabled=state.busy.has(`complete:${state.selectedFinalizeId}`);button.setAttribute("aria-disabled",String(!(amount>0&&validPayment)));}
  if(message){message.textContent=!amount?"Ingresá un monto válido para continuar.":!validPayment?"Seleccioná un medio de pago para completar la derivación.":"Listo para confirmar la carga.";message.classList.toggle("derivation-payment-required",!validPayment);}
}
function focusFinalizeInvalid(){
  const modal=$("derivationFinalizeBackdrop")?.querySelector(".derivation-modal"),amountInput=$("derivationFinalAmount"),paymentGrid=$("derivationFinalizeBackdrop")?.querySelector(".derivation-payment-grid"),message=$("derivationFinalizeMessage");
  const amount=parseCurrencyInput(amountInput?.value);
  let target;
  if(!(amount>0)){target=amountInput;amountInput?.setAttribute("aria-invalid","true");if(message)message.textContent="Ingresá un monto válido para continuar.";}
  else if(!["cash","transfer","card","other"].includes(state.selectedPayment)){target=paymentGrid;paymentGrid?.setAttribute("aria-invalid","true");paymentGrid?.classList.add("is-invalid");if(message)message.textContent="Seleccioná un medio de pago para completar la derivación.";}
  if(target){window.ExploraScrollElementInside?.(modal,target,{top:18,bottom:30});requestAnimationFrame(()=>{const focusable=target.matches?.('input,button')?target:target.querySelector?.('button,input');focusable?.focus?.({preventScroll:true});});return true;}
  return false;
}
async function complete(button){
  const id=state.selectedFinalizeId,method=state.selectedPayment,finalAmount=parseCurrencyInput($("derivationFinalAmount")?.value);
  if(!id||state.busy.has(`complete:${id}`))return;
  let runtime={functionName:"complete",derivationId:id,status:STATUS.INVOICED,receptorUid:uid(),weeklyPeriodId:currentPeriod(),finalAmount,paymentMethod:method,firestoreConfirmed:false};
  state.busy.add(`complete:${id}`);button.disabled=true;button.textContent="CONFIRMANDO…";let committed=null;
  try{
    const me=await ensureSession();
    if(!(finalAmount>0))throw Object.assign(new Error("El monto real debe ser mayor a cero."),{code:"FINAL_AMOUNT_REQUIRED"});
    if(!["cash","transfer","card","other"].includes(method))throw Object.assign(new Error("Selecciona una forma de pago."),{code:"PAYMENT_METHOD_REQUIRED"});
    const period=currentPeriod(),billingId=`derivation_${id}`,collaborationAmount=Math.round(finalAmount*COLLABORATION_RATE);
    runtime={...runtime,collaborationAmount,derivedAmount:finalAmount,firestorePath:`derivaciones/${id}`};
    await runTransaction(db,async tx=>{
      const reference=doc(db,"derivaciones",id),snapshot=await tx.get(reference);
      if(!snapshot.exists())throw Object.assign(new Error("La derivación ya no existe."),{code:"DERIVATION_NOT_FOUND"});
      const row=snapshot.data(),status=canonicalStatus(row);
      if(status===STATUS.INVOICED){committed={row:{...row,id},billing:null,alreadyCompleted:true};return;}
      if(![STATUS.ACCEPTED,STATUS.PENDING_INVOICE].includes(status)||String(row.receptorUid||row.receiverUid)!==me.uid)throw Object.assign(new Error("La derivación no está disponible para facturar."),{code:"INVOICE_TRANSITION_DENIED"});
      const emitterUid=String(row.emisorUid||row.senderUid||"").trim();
      if(!emitterUid||emitterUid===me.uid)throw Object.assign(new Error("UID emisor inválido."),{code:"EMITTER_UID_INVALID"});
      const billingReference=doc(db,"billing_records",billingId),billingSnapshot=await tx.get(billingReference);
      const billing={billingId,operationId:billingId,driverUid:me.uid,choferUid:me.uid,uid:me.uid,driverName:row.receptorName||row.receiverName||"Chofer",amount:finalAmount,monto:finalAmount,finalPrice:finalAmount,paymentMethod:method,metodoPago:method,financialCategory:method,paymentProvider:"derivation",paymentStatus:"completed",status:"completed",estado:"completado",source:"derivation",derivationId:id,originalSenderUid:emitterUid,emisorUid:emitterUid,receptorUid:me.uid,weeklyPeriodId:period,periodoSemanalId:period,collaborationRate:COLLABORATION_RATE,collaborationAmount,createdAt:serverTimestamp(),completedAt:serverTimestamp(),updatedAt:serverTimestamp()};
      if(!billingSnapshot.exists())tx.set(billingReference,billing);
      tx.update(reference,{weeklyPeriodId:period,weeklyPeriodIdCompleted:period,status:STATUS.INVOICED,estado:STATUS.INVOICED,finalAmount,paymentMethod:method,invoicedAt:serverTimestamp(),completedAt:serverTimestamp(),completedByUid:me.uid,billingRecordId:billingId,collaborationRate:COLLABORATION_RATE,collaborationAmount,derivedAmountForEmitter:finalAmount,performanceQualified:true,performanceAwardedToUid:emitterUid,updatedAt:serverTimestamp()});
      committed={row:{...row,id,status:STATUS.INVOICED,weeklyPeriodId:period,weeklyPeriodIdCompleted:period,finalAmount,paymentMethod:method,collaborationRate:COLLABORATION_RATE,collaborationAmount,derivedAmountForEmitter:finalAmount,emisorUid:emitterUid,receptorUid:me.uid},billing};
    });
    runtime.firestoreConfirmed=true;
    if(committed&&!committed.alreadyCompleted){
      const emitterUid=String(committed.row.emisorUid||committed.row.senderUid);
      const integrations=[
        ["UPDATE_DERIVATION_RANKING",()=>window.ExploraWeeklyEngine?.applyDerivationMoneyForUid?.(emitterUid,{...committed.row,participantRole:"emitter"})],
        ["INTEGRATE_WEEKLY_CLOSURE",()=>window.ExploraWeeklyEngine?.applyDerivationMoneyForUid?.(me.uid,{...committed.row,participantRole:"receiver"})],
        ["UPDATE_DERIVATION_RANKING",()=>window.ExploraPerformanceEngine?.refresh?.({force:true,reason:"derivation-invoiced"})]
      ];
      for(const [stage,operation] of integrations){
        try{await operation();}
        catch(error){reportDerivationError(stage,"DERIVATION_POST_COMMIT_SYNC_FAILED",error,{...runtime,emisorUid:emitterUid,receptorUid:me.uid,firestoreConfirmed:true});}
      }
      window.dispatchEvent(new CustomEvent("explora:derivacion-completada",{detail:committed.row}));
      window.invalidateWeeklyFinancialEngine?.("derivation-invoiced");
      window.ExploraInvalidateWeeklyClosure?.("derivation-invoiced",{refresh:false});
      window.ExploraAdminShared?.invalidate?.("derivation-invoiced");
    }
    closeFinalize();await loadPendingCompletion();
    const savedAmount=Number(committed?.row?.finalAmount||finalAmount),savedCollaboration=Number(committed?.row?.collaborationAmount||Math.round(savedAmount*COLLABORATION_RATE));
    window.showExploraSuccess?.({title:"DERIVACIÓN FACTURADA",message:`Se registraron ${money(savedAmount)} derivados y ${money(savedCollaboration)} de colaboración para bono.`});
  }catch(error){
    const stage=String(error?.code||"").includes("REQUIRED")?"VALIDATE_RECEIVER_INVOICE":"CONFIRM_DERIVATION_INVOICE";
    reportDerivationError(stage,"DERIVATION_INVOICE_FAILED",error,runtime);
    const message=$("derivationFinalizeMessage");if(message)message.textContent=error?.message||"No se pudo confirmar la derivación.";
  }finally{state.busy.delete(`complete:${id}`);button.disabled=false;button.textContent="CONFIRMAR CARGA";updateFinalizeButton();}
}
function open(options={}){try{state.opened=true;setDerivationTab(options?.tab==="create"?"create":"received");state.previousScrollY=window.scrollY||0;$("derivationScreen")?.classList.add("is-open");$("derivationScreen")?.setAttribute("aria-hidden","false");window.lockPageScroll?.("derivation-screen");window.ExploraMainNav?.setActive?.("inicio");loadDrivers().then(()=>{renderDrivers();updateCompose();setTimeout(()=>window.ExploraUIRankingGoalsDerivationsRepair?.audit?.("derivar-servicio"),120);}).catch(()=>{});loadPendingCompletion().catch(()=>{});}catch(error){reportDerivationError("OPEN_DERIVATION_MENU","DERIVATION_MENU_OPEN_FAILED",error,{functionName:"open"});}}
function close(){state.opened=false;$("derivationScreen")?.classList.remove("is-open");$("derivationScreen")?.setAttribute("aria-hidden","true");window.unlockPageScroll?.("derivation-screen");window.ExploraMainNav?.setActive?.("inicio");requestAnimationFrame(()=>window.scrollTo(0,state.previousScrollY||0));}
function stop(){try{state.unsubscribe?.();}catch(_){}state.unsubscribe=null;state.pendingResponse=[];state.pendingCompletion=[];state.allReceived=[];state.renderSignature="";state.drivers=[];state.driverMap.clear();window.ExploraDashboardNoticeController?.clearDerivationPending?.();resetForm();renderPendingNotifications();renderReceivedWorkflow();close();closeFinalize();}
window.ExploraActions=window.ExploraActions||{};window.ExploraActions["derivar-servicio"]=()=>open({tab:"received"});window.ExploraOpenNewDerivation=()=>open({tab:"create"});
window.ExploraDerivations={open,close,startForCurrentSession:async()=>{await loadDrivers().catch(()=>{});renderDrivers();startPendingListener();await loadPendingCompletion().catch(()=>{});},stopSession:stop,refresh:async()=>{await loadDrivers(true);renderDrivers();await loadPendingCompletion();},getState:()=>state};
document.addEventListener("DOMContentLoaded",()=>{renderDrivers();updateCompose();renderReceivedWorkflow();$("derivationBackBtn")?.addEventListener("click",close);$("derivationCancelBtn")?.addEventListener("click",()=>setDerivationTab("received"));$("derivationRefreshBtn")?.addEventListener("click",()=>window.ExploraDerivations.refresh().catch(error=>reportDerivationError("READ_INCOMING_DERIVATIONS","DERIVATION_REFRESH_FAILED",error,{functionName:"refresh"})));$("derivationForm")?.addEventListener("submit",sendDerivation);$("derivationDescription")?.addEventListener("input",updateCompose);$("derivationAmount")?.addEventListener("input",event=>{event.target.value=formatCurrencyInput(event.target.value);updateCompose();});$("derivationFinalAmount")?.addEventListener("input",event=>{event.target.value=formatCurrencyInput(event.target.value);updateFinalizeButton();});document.addEventListener("click",event=>{const tab=event.target.closest?.("[data-derivation-tab]");if(tab){setDerivationTab(tab.dataset.derivationTab);return;}const driver=event.target.closest?.("[data-select-derivation-driver]");if(driver){state.selectedReceiverUid=driver.dataset.selectDerivationDriver;renderDrivers();updateCompose();return;}const action=event.target.closest?.("[data-derivation-action]");if(action){transition(action.dataset.derivationId,action.dataset.derivationAction,action);return;}const reminder=event.target.closest?.("[data-reminder-finalize]");if(reminder){openFinalize(reminder.dataset.reminderFinalize);return;}const reject=event.target.closest?.("[data-derivation-final-reject]");if(reject){rejectDefinitively(reject.dataset.derivationFinalReject,reject);}});$("derivationFinalizeCancelBtn")?.addEventListener("click",closeFinalize);$("derivationFinalizeRejectBtn")?.addEventListener("click",event=>rejectDefinitively(state.selectedFinalizeId,event.currentTarget));$("derivationFinalizeConfirmBtn")?.addEventListener("click",event=>complete(event.currentTarget));document.querySelectorAll("[data-derivation-payment]").forEach(paymentButton=>paymentButton.addEventListener("click",()=>{state.selectedPayment=paymentButton.dataset.derivationPayment;const grid=paymentButton.closest(".derivation-payment-grid");grid?.removeAttribute("aria-invalid");grid?.classList.remove("is-invalid");document.querySelectorAll("[data-derivation-payment]").forEach(item=>item.classList.toggle("is-selected",item===paymentButton));updateFinalizeButton();}));});
window.addEventListener("explora:session-opened",event=>{if(!normalize(event.detail?.role).includes("admin"))window.ExploraDerivations.startForCurrentSession().catch(error=>reportDerivationError("INIT","DERIVATION_START_FAILED",error,{functionName:"startForCurrentSession"}));});
window.addEventListener("explora:auth-cleared",stop);
