
import { collection, getDocs, query, where, doc, getDoc, setDoc, updateDoc, serverTimestamp, runTransaction, Timestamp, increment, writeBatch } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { weeklyPeriodFromDate } from "../core/weekly-core.mjs?v2442-weekly-payment-production";

(()=>{
  "use strict";
  if(window.ExploraAdminDriverSimulation)return;
  const MODULE="SIMULATION_RANKING_REPAIR";
  const CONFIG_COLLECTION="simulaciones_choferes";
  const CLAIM_COLLECTION="simulation_operations";
  const TZ="America/Argentina/Cordoba";
  const PAYMENT_TIMES=Object.freeze(["07:00","18:00"]);
  const EXPENSE_TIMES=Object.freeze(["07:00","18:00"]);
  const PAYMENT_VALUES=Object.freeze([25000,60000,10000,35000,8000,82000]);
  const EXPENSE_VALUES=Object.freeze([10000,60000,40000,30000]);
  const EXPENSE_TYPES=Object.freeze(["combustible","peaje","mantenimiento","otros"]);
  const MAX_SLOTS_PER_RUN=62;
  const $=id=>document.getElementById(id);
  const state={drivers:[],configs:new Map(),selectedUid:"",busy:false,catchupPromise:null,lastDiagnostic:"",diagnosticKeys:new Set()};
  let db=null,auth=null;

  const normalize=value=>String(value??"").trim().toLowerCase();
  const safeId=value=>String(value||"").replace(/[^a-zA-Z0-9_-]/g,"_").slice(0,72);
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  const shortUid=value=>String(value||"").slice(0,10)||"—";
  function role(){return normalize(window.ExploraSession?.role||window.ExploraSession?.profile?.role||window.ExploraSession?.profile?.rol||(document.body.classList.contains("explora-shared-admin")?"admin":"chofer"));}
  function isAdmin(){const value=role();return value.includes("admin")||value.includes("owner")||value.includes("superadmin");}
  function toMs(value){if(!value)return 0;if(typeof value.toMillis==="function")return value.toMillis();if(value instanceof Date)return value.getTime();if(typeof value==="number")return value;const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:0;}
  function formatDate(value){const ms=toMs(value);if(!ms)return"Sin ejecución";try{return new Intl.DateTimeFormat("es-AR",{timeZone:TZ,day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(ms));}catch(_){return new Date(ms).toLocaleString("es-AR");}}
  function argentinaParts(date=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(date).reduce((acc,p)=>{if(p.type!=="literal")acc[p.type]=Number(p.value);return acc;},{});}
  function dateKeyFromMs(ms){const p=argentinaParts(new Date(ms));return`${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`;}
  function localSlotMs(dateKey,time){const [y,m,d]=dateKey.split("-").map(Number),[h,min]=time.split(":").map(Number);return Date.UTC(y,m-1,d,h+3,min,0,0);}
  function addDays(dateKey,days){const [y,m,d]=dateKey.split("-").map(Number),date=new Date(Date.UTC(y,m-1,d)+days*86400000);return`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`;}
  function startOfArgentinaDay(ms=Date.now()){return localSlotMs(dateKeyFromMs(ms),"00:00");}
  function periodIdsForMs(ms){const date=new Date(ms),p=argentinaParts(date),weeklyPeriodId=weeklyPeriodFromDate(date,TZ).id;return{weeklyPeriodId,monthlyPeriodId:`${p.year}-${String(p.month).padStart(2,"0")}`,yearlyPeriodId:String(p.year),year:p.year,month:p.month,dateKey:`${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}`};}
  function nextRuns(now=Date.now()){const today=dateKeyFromMs(now),runs=[];for(let offset=0;offset<4&&runs.length<4;offset++){const dateKey=addDays(today,offset);for(const time of PAYMENT_TIMES){const ms=localSlotMs(dateKey,time);if(ms>now)runs.push(new Date(ms).toISOString());if(runs.length>=4)break;}}return runs;}
  function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
  function pick(values,key){return values[hash(key)%values.length];}
  function driverName(data,id){return String(data.nombre||data.nombreCompleto||data.displayName||data.name||data.usuario||id||"Chofer").trim();}
  function driverPhoto(data){return String(data.avatarUrl||data.fotoPerfil||data.photoURL||data.photoUrl||data.avatar||"").trim();}
  function driverUid(data,id){return String(data.uid||data.authUid||data.driverUid||data.choferUid||id||"").trim();}
  function isDriverProfile(data){const r=normalize(data.role||data.rol||data.tipo||data.userRole);return r==="driver"||r==="chofer"||r.includes("chofer")||r.includes("driver");}
  function getSelected(){return state.drivers.find(item=>item.uid===state.selectedUid)||null;}
  function getConfig(uid){return state.configs.get(uid)||null;}
  function setStatus(message,type=""){const el=$("adminDriverSimulationStatus");if(!el)return;el.textContent=message||"";el.className=`admin-driver-simulation-status${type?` is-${type}`:""}`;}
  function lockPage(key){window.lockPageScroll?.(key);}
  function unlockPage(key){window.unlockPageScroll?.(key);}

  function diagnostic(stage,code,error,context={}){
    const driverUidValue=String(context.driverUid||state.selectedUid||"");
    const signature=[MODULE,stage,code,driverUidValue].join("|");
    try{if(state.diagnosticKeys.has(signature)||sessionStorage.getItem(`explora_sim_diag_${signature}`)==="1")return;state.diagnosticKeys.add(signature);sessionStorage.setItem(`explora_sim_diag_${signature}`,"1");}catch(_){if(state.diagnosticKeys.has(signature))return;state.diagnosticKeys.add(signature);}
    const payload=[
      "EXPLORA - ERROR SIMULATION_RANKING_REPAIR",`MÓDULO: ${MODULE}`,`ETAPA: ${stage||"INIT"}`,`CÓDIGO INTERNO: ${code||"SIMULATION_UNKNOWN_ERROR"}`,
      `MENSAJE REAL FIREBASE: ${error?.code||"—"} · ${error?.message||"—"}`,`MENSAJE REAL JAVASCRIPT: ${error?.message||String(error||"—")}`,`STACK: ${error?.stack||"—"}`,
      `FUNCIÓN: ${context.functionName||"—"}`,`UID AUTH: ${auth?.currentUser?.uid||"—"}`,`ADMIN UID: ${isAdmin()?auth?.currentUser?.uid||"—":"—"}`,`ROL: ${role()||"—"}`,
      `DRIVER UID: ${driverUidValue||"—"}`,`SIMULATION DRIVER UID: ${context.simulationDriverUid||driverUidValue||"—"}`,`DRIVER NAME: ${context.driverName||getSelected()?.name||"—"}`,`SIMULATION ID: ${context.simulationId||"—"}`,
      `WEEKLY PERIOD ID: ${context.weeklyPeriodId||"—"}`,
      `COBROS SIMULADOS LEÍDOS: ${context.simulatedPaymentsRead??"—"}`,`GASTOS SIMULADOS LEÍDOS: ${context.simulatedExpensesRead??"—"}`,
      `FACTURASTE CALCULADA: ${context.calculatedBilling??"—"}`,`GASTOS CALCULADOS: ${context.calculatedExpenses??"—"}`,
      `CACHE HIT: ${context.cacheHit===true?"SÍ":context.cacheHit===false?"NO":"—"}`,`CACHE MISS: ${context.cacheMiss===true?"SÍ":context.cacheMiss===false?"NO":"—"}`,
      `RUTA FIRESTORE: ${context.firestorePath||"—"}`,`QUERY USADA: ${context.queryUsed||"—"}`,`DOCUMENTOS CREADOS: ${context.documentsCreated??"—"}`,`DOCUMENTOS BORRADOS: ${context.documentsDeleted??"—"}`,
      `LAST RUN AT: ${context.lastRunAt||"—"}`,`NEXT RUNS: ${Array.isArray(context.nextRuns)?context.nextRuns.join(" | "):context.nextRuns||"—"}`,`TIMESTAMP: ${new Date().toISOString()}`
    ].join("\n");
    state.lastDiagnostic=payload;const text=$("adminDriverSimulationDiagnosticText");if(text)text.textContent=payload;const panel=$("adminDriverSimulationDiagnostic");panel?.classList.add("is-open");panel?.setAttribute("aria-hidden","false");lockPage("simulation-diagnostic");
  }
  function closeDiagnostic(){const panel=$("adminDriverSimulationDiagnostic");panel?.classList.remove("is-open");panel?.setAttribute("aria-hidden","true");unlockPage("simulation-diagnostic");}
  async function copyDiagnostic(){try{await navigator.clipboard.writeText(state.lastDiagnostic||$("adminDriverSimulationDiagnosticText")?.textContent||"");}catch(_){const area=document.createElement("textarea");area.value=state.lastDiagnostic||"";document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();}}

  async function waitFirebase(){for(let i=0;i<120;i++){const F=window.ExploraFirebase;if(F?.db&&F?.auth){db=F.db;auth=F.auth;return F;}await new Promise(r=>setTimeout(r,50));}throw Object.assign(new Error("Firebase no está disponible para simulaciones."),{code:"SIMULATION_FIREBASE_UNAVAILABLE"});}

  async function readDrivers(){
    try{await waitFirebase();const snapshot=await getDocs(collection(db,"choferes"));const rows=[];snapshot.forEach(item=>{const data=item.data()||{};if(!isDriverProfile(data))return;const uid=driverUid(data,item.id);if(!uid)return;rows.push({id:item.id,uid,name:driverName(data,item.id),photo:driverPhoto(data),raw:data});});rows.sort((a,b)=>a.name.localeCompare(b.name,"es"));state.drivers=rows;return rows;}
    catch(error){diagnostic("READ_DRIVERS","SIMULATION_DRIVER_READ_FAILED",error,{functionName:"readDrivers",firestorePath:"choferes",queryUsed:"getDocs(collection(choferes))"});throw error;}
  }
  async function readConfigs(){await waitFirebase();const snapshot=await getDocs(collection(db,CONFIG_COLLECTION));const map=new Map();snapshot.forEach(item=>map.set(item.id,{id:item.id,...(item.data()||{})}));state.configs=map;return map;}
  async function readActiveConfigs(){await waitFirebase();const snapshot=await getDocs(query(collection(db,CONFIG_COLLECTION),where("isSimulationActive","==",true)));return snapshot.docs.map(item=>({id:item.id,...(item.data()||{})}));}

  function render(){
    const list=$("adminDriverSimulationList");if(!list)return;const activeCount=[...state.configs.values()].filter(c=>c.isSimulationActive===true).length,totalRecords=[...state.configs.values()].reduce((sum,c)=>sum+Number(c.simulatedPaymentCount||0)+Number(c.simulatedExpenseCount||0),0);
    $("adminSimulationDriverCount").textContent=String(state.drivers.length);$("adminSimulationActiveCount").textContent=String(activeCount);$("adminSimulationRecordCount").textContent=String(totalRecords);
    if(!state.drivers.length){list.innerHTML='<div class="admin-driver-simulation-empty">No hay perfiles con rol Chofer disponibles.</div>';renderSelected();return;}
    const fragment=document.createDocumentFragment();for(const driver of state.drivers){const config=getConfig(driver.uid),active=config?.isSimulationActive===true,button=document.createElement("button");button.type="button";button.className=`admin-driver-simulation-card${active?" is-active":""}${state.selectedUid===driver.uid?" is-selected":""}`;button.dataset.simulationDriverUid=driver.uid;button.innerHTML=`<img class="admin-driver-simulation-avatar" alt="" src="${escapeHtml(driver.photo||"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Crect width='80' height='80' rx='40' fill='%2313191f'/%3E%3Ccircle cx='40' cy='31' r='14' fill='%23d7b254'/%3E%3Cpath d='M16 72c3-17 13-25 24-25s21 8 24 25' fill='%23d7b254'/%3E%3C/svg%3E")}"><span class="admin-driver-simulation-copy"><strong>${escapeHtml(driver.name)}</strong><small>UID ${escapeHtml(shortUid(driver.uid))} · Última: ${escapeHtml(formatDate(config?.lastRunAt))}</small><em>${Number(config?.simulatedPaymentCount||0)} cobros · ${Number(config?.simulatedExpenseCount||0)} gastos</em></span><span class="admin-driver-simulation-badge${active?" is-active":""}">${active?"ACTIVA":"INACTIVA"}</span>`;fragment.appendChild(button);}list.replaceChildren(fragment);renderSelected();
  }
  function renderSelected(){const detail=$("adminDriverSimulationDetail"),driver=getSelected();if(!detail)return;if(!driver){detail.classList.remove("is-visible");return;}const config=getConfig(driver.uid),active=config?.isSimulationActive===true,paymentCount=Number(config?.simulatedPaymentCount||0),expenseCount=Number(config?.simulatedExpenseCount||0),cleanupPending=config?.cleanupPending===true||paymentCount>0||expenseCount>0,next=Array.isArray(config?.nextRuns)&&config.nextRuns.length?formatDate(config.nextRuns[0]):formatDate(nextRuns()[0]);detail.classList.add("is-visible");$("adminSimulationSelectedName").textContent=driver.name;$("adminSimulationSelectedState").textContent=active?"Simulación activa":config?.cleanupPending===true?"Limpieza pendiente":"Simulación inactiva";$("adminSimulationSelectedUid").textContent=driver.uid;$("adminSimulationSelectedLastRun").textContent=formatDate(config?.lastRunAt);$("adminSimulationSelectedNextRun").textContent=next;$("adminSimulationSelectedPayments").textContent=String(paymentCount);$("adminSimulationSelectedExpenses").textContent=String(expenseCount);$("adminDriverSimulationStart").disabled=state.busy||active||cleanupPending;$("adminDriverSimulationStop").disabled=state.busy||(!active&&!cleanupPending);}

  async function loadScreen(){if(!isAdmin()){diagnostic("ADMIN_ONLY_CHECK","SIMULATION_ADMIN_ONLY",new Error("Sólo Administrador puede abrir Simular Choferes."),{functionName:"loadScreen"});return;}setStatus("Cargando choferes…");try{await Promise.all([readDrivers(),readConfigs()]);render();setStatus("");}catch(error){setStatus("No se pudo cargar el módulo de simulación.","error");}}
  async function open(){if(!isAdmin()){diagnostic("ADMIN_ONLY_CHECK","SIMULATION_ADMIN_ONLY",new Error("Sólo Administrador puede abrir Simular Choferes."),{functionName:"open"});return;}const screen=$("adminDriverSimulationScreen");if(screen?.classList.contains("is-open"))return;screen?.classList.add("is-open");screen?.setAttribute("aria-hidden","false");lockPage("admin-driver-simulation");await loadScreen();}
  function close(){const screen=$("adminDriverSimulationScreen");screen?.classList.remove("is-open");screen?.setAttribute("aria-hidden","true");unlockPage("admin-driver-simulation");}

  async function startSimulation(){
    if(!isAdmin()){diagnostic("ADMIN_ONLY_CHECK","SIMULATION_ADMIN_ONLY",new Error("Sólo Administrador puede activar simulaciones."),{functionName:"startSimulation"});return;}const driver=getSelected();if(!driver){diagnostic("SELECT_DRIVER","SIMULATION_INVALID_DRIVER",new Error("Seleccioná un chofer válido."),{functionName:"startSimulation"});return;}if(!isDriverProfile(driver.raw)){diagnostic("SELECT_DRIVER","SIMULATION_INVALID_DRIVER",new Error("El perfil seleccionado no posee rol Chofer."),{functionName:"startSimulation",driverUid:driver.uid,driverName:driver.name});return;}
    state.busy=true;renderSelected();setStatus("Activando simulación…");const now=Date.now(),configRef=doc(db,CONFIG_COLLECTION,driver.uid);
    try{await setDoc(configRef,{driverUid:driver.uid,driverDocumentId:driver.id,driverName:driver.name,driverPhotoUrl:driver.photo||"",isSimulationActive:true,schemaVersion:234,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),startedAt:serverTimestamp(),startedByUid:auth.currentUser.uid,startedByRole:"admin",lastRunAt:Timestamp.fromMillis(startOfArgentinaDay(now)-1),nextRuns:nextRuns(now),dailyPaymentTimes:[...PAYMENT_TIMES],dailyExpenseTimes:[...EXPENSE_TIMES],paymentValues:[...PAYMENT_VALUES],expenseValues:[...EXPENSE_VALUES],simulatedPaymentCount:0,simulatedExpenseCount:0,simulationSource:"ADMIN_DRIVER_SIMULATION"},{merge:true});await runCatchup({silent:false,driverUid:driver.uid});await readConfigs();render();setStatus("Simulación activa. Los registros pendientes fueron procesados.","ok");}
    catch(error){diagnostic("START_SIMULATION",error?.code==="permission-denied"?"SIMULATION_CONFIG_WRITE_FAILED":"SIMULATION_START_FAILED",error,{functionName:"startSimulation",driverUid:driver.uid,driverName:driver.name,firestorePath:`${CONFIG_COLLECTION}/${driver.uid}`,queryUsed:"setDoc merge + catch-up"});setStatus("No se pudo activar la simulación.","error");}
    finally{state.busy=false;renderSelected();}
  }

  function enumerateDueSlots(config,now=Date.now()){
    const cursor=Math.max(0,toMs(config.lastRunAt)||toMs(config.startedAt)||now),startDate=addDays(dateKeyFromMs(cursor),-1),endDate=dateKeyFromMs(now),slots=[];let dateKey=startDate,guard=0;
    while(dateKey<=endDate&&guard<370){for(const time of PAYMENT_TIMES){const ms=localSlotMs(dateKey,time);if(ms>cursor&&ms<=now)slots.push({dateKey,time,ms});}dateKey=addDays(dateKey,1);guard++;}
    slots.sort((a,b)=>a.ms-b.ms);return slots.slice(0,MAX_SLOTS_PER_RUN);
  }
  function simulationId(config,slot,type){return`sim_${safeId(config.driverUid)}_${slot.dateKey}_${slot.time.replace(":","")}_${type}`;}
  function paymentPayload(config,slot,id){const amount=pick(PAYMENT_VALUES,id),periods=periodIdsForMs(slot.ms),stamp=Timestamp.fromMillis(slot.ms),adminUid=config.startedByUid||auth?.currentUser?.uid||"";return{schemaVersion:234,billingId:id,id,operationId:id,driverUid:config.driverUid,simulationDriverUid:config.driverUid,uid:config.driverUid,choferUid:config.driverUid,choferId:config.driverDocumentId||config.driverUid,profileDocumentId:config.driverDocumentId||config.driverUid,driverName:config.driverName||"Chofer",amount,monto:amount,valor:amount,grossAmount:amount,billingAmount:amount,total:amount,finalPrice:amount,paymentMethod:"cash",metodoPago:"cash",financialCategory:"cash",type:"billing",verificationMode:"simulation",paymentProvider:"simulation",paymentStatus:"confirmed",status:"confirmado",estado:"confirmado",confirmed:true,isConfirmed:true,completado:true,source:"admin_driver_simulation",weeklyPeriodId:periods.weeklyPeriodId,periodoSemanalId:periods.weeklyPeriodId,periodoId:periods.weeklyPeriodId,monthlyPeriodId:periods.monthlyPeriodId,yearlyPeriodId:periods.yearlyPeriodId,year:periods.year,month:periods.month,fecha:new Intl.DateTimeFormat("es-AR",{timeZone:TZ}).format(new Date(slot.ms)),hora:slot.time,paymentDate:stamp,serviceDate:stamp,sourceCreatedAt:stamp,isSimulated:true,simulationId:id,createdBySimulation:true,createdByUid:config.driverUid,createdByRole:"chofer",simulatedByAdminUid:adminUid,simulatedAt:stamp,simulationRecordedAt:serverTimestamp(),simulationSlot:`${slot.dateKey} ${slot.time}`,simulationSource:"ADMIN_DRIVER_SIMULATION",simulationWithoutReceipt:true,createdAt:serverTimestamp(),completedAt:serverTimestamp(),confirmedAt:serverTimestamp(),invoicedAt:serverTimestamp(),updatedAt:serverTimestamp()};}
  function expensePayload(config,slot,id){const amount=pick(EXPENSE_VALUES,id),expenseType=pick(EXPENSE_TYPES,`${id}_category`),periods=periodIdsForMs(slot.ms),stamp=Timestamp.fromMillis(slot.ms),adminUid=config.startedByUid||auth?.currentUser?.uid||"";return{schemaVersion:234,expenseId:id,gastoId:id,id,operationId:id,driverUid:config.driverUid,simulationDriverUid:config.driverUid,choferUid:config.driverUid,uid:config.driverUid,choferId:config.driverDocumentId||config.driverUid,profileDocumentId:config.driverDocumentId||config.driverUid,driverName:config.driverName||"Chofer",expenseType,tipo:expenseType,categoria:expenseType,amount,monto:amount,total:amount,notes:"Gasto operativo simulado",observaciones:"Gasto operativo simulado",weeklyPeriodId:periods.weeklyPeriodId,periodoSemanalId:periods.weeklyPeriodId,periodoId:periods.weeklyPeriodId,monthlyPeriodId:periods.monthlyPeriodId,yearlyPeriodId:periods.yearlyPeriodId,status:"confirmado",estado:"confirmado",confirmed:true,isConfirmed:true,expenseDate:stamp,sourceCreatedAt:stamp,isSimulated:true,simulationId:id,createdBySimulation:true,createdByUid:config.driverUid,createdByRole:"chofer",simulatedByAdminUid:adminUid,simulatedAt:stamp,simulationRecordedAt:serverTimestamp(),simulationSlot:`${slot.dateKey} ${slot.time}`,simulationSource:"ADMIN_DRIVER_SIMULATION",simulationWithoutReceipt:true,receiptUrl:null,receiptPath:null,createdAt:serverTimestamp(),confirmedAt:serverTimestamp(),updatedAt:serverTimestamp()};}

  function validateSimulatedPayload(payload,type){
    const amount=Number(payload?.amount||0),driverUidValue=String(payload?.driverUid||payload?.simulationDriverUid||"").trim(),weeklyPeriodId=String(payload?.weeklyPeriodId||"").trim();
    if(!driverUidValue)throw Object.assign(new Error("El registro simulado no contiene driverUid."),{code:"SIMULATED_PAYMENT_MISSING_DRIVER_UID"});
    if(!(amount>0))throw Object.assign(new Error(`El ${type==="payment"?"cobro":"gasto"} simulado no contiene un monto válido.`),{code:type==="payment"?"SIMULATED_PAYMENT_MISSING_AMOUNT":"SIMULATED_EXPENSE_MISSING_AMOUNT"});
    if(!weeklyPeriodId)throw Object.assign(new Error("El registro simulado no contiene weeklyPeriodId."),{code:"SIMULATED_PAYMENT_MISSING_WEEKLY_PERIOD"});
    return true;
  }
  function simulatedRecordPatch(data,id,config,type){
    const sourceMs=toMs(data?.paymentDate||data?.expenseDate||data?.simulatedAt||data?.sourceCreatedAt||data?.createdAt)||Date.now(),periods=periodIdsForMs(sourceMs),amount=Math.max(0,Number(data?.amount??data?.monto??data?.grossAmount??data?.total??0)||0),stamp=Timestamp.fromMillis(sourceMs),base={schemaVersion:234,id:data?.id||id,operationId:data?.operationId||id,driverUid:config.driverUid,simulationDriverUid:config.driverUid,uid:config.driverUid,choferUid:config.driverUid,choferId:config.driverDocumentId||data?.choferId||config.driverUid,profileDocumentId:config.driverDocumentId||data?.profileDocumentId||config.driverUid,driverName:config.driverName||data?.driverName||"Chofer",amount,monto:amount,total:amount,weeklyPeriodId:periods.weeklyPeriodId,periodoSemanalId:periods.weeklyPeriodId,periodoId:periods.weeklyPeriodId,monthlyPeriodId:periods.monthlyPeriodId,yearlyPeriodId:periods.yearlyPeriodId,isSimulated:true,createdBySimulation:true,createdByUid:config.driverUid,createdByRole:"chofer",simulationSource:"ADMIN_DRIVER_SIMULATION",simulationRecordedAt:serverTimestamp(),updatedAt:serverTimestamp()};
    if(type==="payment")return{...base,billingId:data?.billingId||id,grossAmount:amount,billingAmount:amount,valor:amount,finalPrice:amount,paymentMethod:data?.paymentMethod||"cash",metodoPago:data?.metodoPago||"cash",financialCategory:data?.financialCategory||"cash",paymentStatus:"confirmed",status:"confirmado",estado:"confirmado",confirmed:true,isConfirmed:true,completado:true,paymentDate:data?.paymentDate||stamp,serviceDate:data?.serviceDate||stamp,sourceCreatedAt:data?.sourceCreatedAt||stamp,completedAt:serverTimestamp(),confirmedAt:serverTimestamp(),invoicedAt:serverTimestamp()};
    return{...base,expenseId:data?.expenseId||id,gastoId:data?.gastoId||id,expenseType:data?.expenseType||data?.tipo||"otros",tipo:data?.tipo||data?.expenseType||"otros",categoria:data?.categoria||data?.expenseType||data?.tipo||"otros",status:"confirmado",estado:"confirmado",confirmed:true,isConfirmed:true,expenseDate:data?.expenseDate||stamp,sourceCreatedAt:data?.sourceCreatedAt||stamp};
  }
  async function normalizeExistingSimulatedRecords(config){
    let payments=0,expenses=0,changed=0;
    for(const [collectionName,type] of [["billing_records","payment"],["gastos","expense"]]){
      const snapshot=await getDocs(query(collection(db,collectionName),where("simulationDriverUid","==",config.driverUid)));
      const candidates=snapshot.docs.filter(item=>item.data()?.isSimulated===true),normalizedRows=[],pending=[];
      for(const item of candidates){const original=item.data()||{},patch=simulatedRecordPatch(original,item.id,config,type);validateSimulatedPayload(patch,type);normalizedRows.push({...original,...patch,id:item.id,operationId:patch.operationId||item.id});const needsPatch=Number(original.schemaVersion||0)<234||!original.driverUid||!original.weeklyPeriodId||Number(original.amount||original.monto||0)<=0||String(original.status||original.estado||"").toLowerCase()!=="confirmado";if(needsPatch)pending.push({ref:item.ref,patch});}
      for(let index=0;index<pending.length;index+=300){const batch=writeBatch(db);pending.slice(index,index+300).forEach(item=>batch.set(item.ref,item.patch,{merge:true}));await batch.commit();changed+=Math.min(300,pending.length-index);}
      for(const row of normalizedRows){try{if(type==="payment")await window.ExploraWeeklyEngine?.applyBilling?.(row);else await window.ExploraWeeklyEngine?.applyExpense?.(row);}catch(error){diagnostic(type==="payment"?"CALCULATE_BILLING_RANKING":"CALCULATE_WEEKLY_EXPENSES",type==="payment"?"RANKING_RENDER_EMPTY_WITH_SIMULATED_DATA":"GOALS_NOT_UPDATED_WITH_SIMULATION",error,{functionName:"normalizeExistingSimulatedRecords",driverUid:config.driverUid,simulationDriverUid:config.driverUid,weeklyPeriodId:row.weeklyPeriodId,firestorePath:"acumulados_semanales",queryUsed:"materialize normalized simulated record"});}}
      if(type==="payment")payments=candidates.length;else expenses=candidates.length;
    }
    return{payments,expenses,changed};
  }
  async function materializeSimulatedRecord(type,result){
    if(!result?.created||!result?.payload)return;
    try{if(type==="payment")await window.ExploraWeeklyEngine?.applyBilling?.(result.payload);else await window.ExploraWeeklyEngine?.applyExpense?.(result.payload);}
    catch(error){diagnostic(type==="payment"?"CALCULATE_BILLING_RANKING":"CALCULATE_WEEKLY_EXPENSES",type==="payment"?"RANKING_RENDER_EMPTY_WITH_SIMULATED_DATA":"GOALS_NOT_UPDATED_WITH_SIMULATION",error,{functionName:"materializeSimulatedRecord",driverUid:result.payload.driverUid,simulationDriverUid:result.payload.simulationDriverUid,weeklyPeriodId:result.payload.weeklyPeriodId,firestorePath:"acumulados_semanales",queryUsed:"ExploraWeeklyEngine.applyBilling/applyExpense",calculatedBilling:type==="payment"?result.payload.amount:0,calculatedExpenses:type==="expense"?result.payload.amount:0});}
  }

  async function rebuildDriverWeeklyMaterialized(driverUidValue,reason="simulation-rebuild"){
    const periods=periodIdsForMs(Date.now());
    try{return await window.ExploraWeeklyEngine?.getDriverWeeklySnapshot?.(driverUidValue,periods.weeklyPeriodId,{force:true,allowLegacyScan:false,reason});}
    catch(error){diagnostic("CALCULATE_WEEKLY_EXPENSES","CACHE_STALE_AFTER_SIMULATION",error,{functionName:"rebuildDriverWeeklyMaterialized",driverUid:driverUidValue,simulationDriverUid:driverUidValue,weeklyPeriodId:periods.weeklyPeriodId,firestorePath:"acumulados_semanales",queryUsed:"getDriverWeeklySnapshot(force:true)"});return null;}
  }

  async function createSimulatedRecord(config,slot,type){
    const id=simulationId(config,slot,type),configRef=doc(db,CONFIG_COLLECTION,config.driverUid),claimRef=doc(db,CLAIM_COLLECTION,id),destRef=doc(db,type==="payment"?"billing_records":"gastos",id),payload=type==="payment"?paymentPayload(config,slot,id):expensePayload(config,slot,id);
    try{validateSimulatedPayload(payload,type);return await runTransaction(db,async tx=>{const [cfgSnap,claimSnap,destSnap]=await Promise.all([tx.get(configRef),tx.get(claimRef),tx.get(destRef)]);if(!cfgSnap.exists()||cfgSnap.data()?.isSimulationActive!==true)return{created:false,inactive:true,id};if(claimSnap.exists())return{created:false,duplicate:true,id};if(destSnap.exists()){tx.set(claimRef,{simulationId:id,driverUid:config.driverUid,type,slotMs:slot.ms,createdAt:serverTimestamp(),recoveredExisting:true});return{created:false,duplicate:true,id};}tx.set(destRef,payload);tx.set(claimRef,{simulationId:id,driverUid:config.driverUid,type,destination:type==="payment"?"billing_records":"gastos",slotMs:slot.ms,slot:`${slot.dateKey} ${slot.time}`,createdAt:serverTimestamp()});tx.update(configRef,{[type==="payment"?"simulatedPaymentCount":"simulatedExpenseCount"]:increment(1),updatedAt:serverTimestamp()});return{created:true,id,payload};});}
    catch(error){const stage=type==="payment"?"NORMALIZE_SIMULATED_PAYMENT":"NORMALIZE_SIMULATED_EXPENSE",fallback=type==="payment"?"SIMULATED_PAYMENT_SCHEMA_INVALID":"SIMULATED_EXPENSE_SCHEMA_INVALID";diagnostic(stage,error?.code||fallback,error,{functionName:"createSimulatedRecord",driverUid:config.driverUid,simulationDriverUid:config.driverUid,driverName:config.driverName,simulationId:id,weeklyPeriodId:payload?.weeklyPeriodId,firestorePath:`${type==="payment"?"billing_records":"gastos"}/${id}`,queryUsed:"runTransaction config + claim + destination"});throw error;}
  }

  async function runCatchup({silent=true,driverUid=""}={}){
    if(state.catchupPromise)return state.catchupPromise;
    state.catchupPromise=(async()=>{await waitFirebase();let configs;try{configs=await readActiveConfigs();}catch(error){if(!silent||isAdmin())diagnostic("RUN_SIMULATION_CATCHUP","SIMULATION_CATCHUP_FAILED",error,{functionName:"readActiveConfigs",firestorePath:CONFIG_COLLECTION,queryUsed:"where(isSimulationActive == true)"});return{created:0};}if(driverUid)configs=configs.filter(item=>item.driverUid===driverUid||item.id===driverUid);let created=0,processedSlots=0;
      for(const config of configs){if(!config.driverUid)continue;try{const normalized=await normalizeExistingSimulatedRecords(config);if(normalized.changed>0)await refreshDependentModules("simulation-schema-normalized",normalized.changed);}catch(error){if(!silent||isAdmin())diagnostic("READ_SIMULATED_PAYMENTS",error?.code||"SIMULATED_PAYMENT_SCHEMA_INVALID",error,{functionName:"normalizeExistingSimulatedRecords",driverUid:config.driverUid,simulationDriverUid:config.driverUid,driverName:config.driverName,firestorePath:"billing_records + gastos",queryUsed:`where(simulationDriverUid == ${config.driverUid})`});}const slots=enumerateDueSlots(config);let processedThrough=toMs(config.lastRunAt)||Date.now();for(const slot of slots){try{const payment=await createSimulatedRecord(config,slot,"payment"),expense=await createSimulatedRecord(config,slot,"expense");if(payment.inactive||expense.inactive)break;if(payment.created){created++;await materializeSimulatedRecord("payment",payment);}if(expense.created){created++;await materializeSimulatedRecord("expense",expense);}processedThrough=slot.ms;processedSlots++;if(processedSlots%4===0)await new Promise(requestAnimationFrame);}catch(error){break;}}try{await updateDoc(doc(db,CONFIG_COLLECTION,config.driverUid),{lastRunAt:Timestamp.fromMillis(Math.max(processedThrough,toMs(config.lastRunAt)||0)),nextRuns:nextRuns(),schemaVersion:234,updatedAt:serverTimestamp()});}catch(error){if(!silent||isAdmin())diagnostic("CACHE_INVALIDATE", "CACHE_STALE_AFTER_SIMULATION",error,{functionName:"updateCatchupCursor",driverUid:config.driverUid,simulationDriverUid:config.driverUid,driverName:config.driverName,firestorePath:`${CONFIG_COLLECTION}/${config.driverUid}`,lastRunAt:formatDate(processedThrough),nextRuns:nextRuns()});}}
      if(created>0)await refreshDependentModules("simulation-catchup",created);return{created,processedSlots};})().finally(()=>{state.catchupPromise=null;});return state.catchupPromise;
  }

  async function deleteQueryDocuments(collectionName,driverUidValue){const snapshot=await getDocs(query(collection(db,collectionName),where("simulationDriverUid","==",driverUidValue)));const refs=snapshot.docs.filter(item=>item.data()?.isSimulated===true&&item.data()?.simulationDriverUid===driverUidValue).map(item=>item.ref);for(let index=0;index<refs.length;index+=350){const batch=writeBatch(db);refs.slice(index,index+350).forEach(ref=>batch.delete(ref));await batch.commit();}return refs.length;}
  async function deleteClaims(driverUidValue){const snapshot=await getDocs(query(collection(db,CLAIM_COLLECTION),where("driverUid","==",driverUidValue)));const refs=snapshot.docs.map(item=>item.ref);for(let index=0;index<refs.length;index+=350){const batch=writeBatch(db);refs.slice(index,index+350).forEach(ref=>batch.delete(ref));await batch.commit();}return refs.length;}
  async function refreshDependentModules(reason,count=0){try{window.invalidateWeeklyFinancialEngine?.(reason);window.ExploraWeeklyEngine?.invalidate?.(reason,{refresh:false});window.ExploraPerformanceEngine?.invalidateRankingCache?.(reason);["dashboard_weekly_billing","dashboard_weekly_expenses","billing_ranking","derivation_ranking","goal_bubbles","performance_bundle","admin_summary"].forEach(name=>window.ExploraFastCache?.invalidate?.(name));window.ExploraAdminShared?.invalidate?.();window.dispatchEvent(new CustomEvent("explora:simulation-updated",{detail:{reason,documentsChanged:count}}));await Promise.allSettled([window.ExploraPerformanceEngine?.refresh?.({force:true,reason}),window.ExploraWeeklyEngine?.refresh?.({force:true,reason})]);}catch(error){diagnostic("CACHE_INVALIDATE","CACHE_STALE_AFTER_SIMULATION",error,{functionName:"refreshDependentModules",documentsCreated:count,cacheHit:false,cacheMiss:true});}}

  function openStopConfirm(){const driver=getSelected(),config=driver&&getConfig(driver.uid),hasData=Number(config?.simulatedPaymentCount||0)>0||Number(config?.simulatedExpenseCount||0)>0||config?.cleanupPending===true;if(!driver||(config?.isSimulationActive!==true&&!hasData))return;const panel=$("adminDriverSimulationConfirm");panel?.classList.add("is-open");panel?.setAttribute("aria-hidden","false");lockPage("simulation-confirm");}
  function closeStopConfirm(){const panel=$("adminDriverSimulationConfirm");panel?.classList.remove("is-open");panel?.setAttribute("aria-hidden","true");unlockPage("simulation-confirm");}
  async function stopSimulation(){
    if(!isAdmin()){diagnostic("ADMIN_ONLY_CHECK","SIMULATION_ADMIN_ONLY",new Error("Sólo Administrador puede detener simulaciones."),{functionName:"stopSimulation"});return;}const driver=getSelected();if(!driver){diagnostic("SELECT_DRIVER","SIMULATION_INVALID_DRIVER",new Error("Seleccioná un chofer válido."),{functionName:"stopSimulation"});return;}state.busy=true;closeStopConfirm();renderSelected();setStatus("Eliminando únicamente datos simulados…");
    try{await updateDoc(doc(db,CONFIG_COLLECTION,driver.uid),{isSimulationActive:false,cleanupPending:true,stoppedAt:serverTimestamp(),stoppedByUid:auth.currentUser.uid,updatedAt:serverTimestamp()});let payments=0,expenses=0,claims=0;try{payments=await deleteQueryDocuments("billing_records",driver.uid);}catch(error){diagnostic("DELETE_SIMULATED_PAYMENTS","SIMULATION_DELETE_PAYMENTS_FAILED",error,{functionName:"deleteQueryDocuments",driverUid:driver.uid,driverName:driver.name,firestorePath:"billing_records",queryUsed:`where(simulationDriverUid == ${driver.uid})`});throw error;}try{expenses=await deleteQueryDocuments("gastos",driver.uid);}catch(error){diagnostic("DELETE_SIMULATED_EXPENSES","SIMULATION_DELETE_EXPENSES_FAILED",error,{functionName:"deleteQueryDocuments",driverUid:driver.uid,driverName:driver.name,firestorePath:"gastos",queryUsed:`where(simulationDriverUid == ${driver.uid})`,documentsDeleted:payments});throw error;}try{claims=await deleteClaims(driver.uid);}catch(error){diagnostic("STOP_SIMULATION","SIMULATION_STOP_FAILED",error,{functionName:"deleteClaims",driverUid:driver.uid,driverName:driver.name,firestorePath:CLAIM_COLLECTION,queryUsed:`where(driverUid == ${driver.uid})`,documentsDeleted:payments+expenses});throw error;}await rebuildDriverWeeklyMaterialized(driver.uid,"simulation-stopped");await updateDoc(doc(db,CONFIG_COLLECTION,driver.uid),{simulatedPaymentCount:0,simulatedExpenseCount:0,cleanupPending:false,lastRunAt:null,nextRuns:[],deletedSimulatedPayments:payments,deletedSimulatedExpenses:expenses,deletedSimulationClaims:claims,lastCleanupAt:serverTimestamp(),updatedAt:serverTimestamp()});await refreshDependentModules("simulation-stopped",payments+expenses);await readConfigs();render();setStatus(`Simulación detenida. ${payments} cobros y ${expenses} gastos simulados eliminados.`,"ok");}
    catch(error){diagnostic("STOP_SIMULATION","SIMULATION_STOP_FAILED",error,{functionName:"stopSimulation",driverUid:driver.uid,driverName:driver.name,firestorePath:`${CONFIG_COLLECTION}/${driver.uid}`});setStatus("No se pudo detener completamente la simulación.","error");}
    finally{state.busy=false;renderSelected();}
  }

  function bind(){
    window.ExploraActions=window.ExploraActions||{};
    window.ExploraActions["admin-simulate-drivers"]=()=>open();
    document.addEventListener("click",event=>{const card=event.target.closest?.("[data-simulation-driver-uid]");if(card){state.selectedUid=card.dataset.simulationDriverUid||"";render();return;}});
    $("adminDriverSimulationBack")?.addEventListener("click",close);$("adminDriverSimulationRefresh")?.addEventListener("click",loadScreen);$("adminDriverSimulationStart")?.addEventListener("click",startSimulation);$("adminDriverSimulationStop")?.addEventListener("click",openStopConfirm);$("adminDriverSimulationConfirmCancel")?.addEventListener("click",closeStopConfirm);$("adminDriverSimulationConfirmStop")?.addEventListener("click",stopSimulation);$("adminDriverSimulationDiagnosticClose")?.addEventListener("click",closeDiagnostic);$("adminDriverSimulationDiagnosticCloseBottom")?.addEventListener("click",closeDiagnostic);$("adminDriverSimulationDiagnosticCopy")?.addEventListener("click",copyDiagnostic);
    window.addEventListener("explora:session-opened",()=>setTimeout(()=>runCatchup({silent:true}).catch(()=>{}),700));document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")setTimeout(()=>runCatchup({silent:true}).catch(()=>{}),600);});
  }

  window.ExploraAdminDriverSimulation={open,close,load:loadScreen,start:startSimulation,stop:stopSimulation,runCatchup,getState:()=>({drivers:[...state.drivers],configs:[...state.configs.values()],selectedUid:state.selectedUid,busy:state.busy})};
  bind();waitFirebase().then(()=>{onAuthStateChanged(auth,user=>{if(user)setTimeout(()=>runCatchup({silent:true}).catch(()=>{}),900);});}).catch(error=>diagnostic("INIT","SIMULATION_CATCHUP_FAILED",error,{functionName:"waitFirebase"}));
})();
