
  import { getApps, getApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
  import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
  import { getFirestore, collection, doc, query, where, onSnapshot } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
  (()=>{
    "use strict";
    if(window.ExploraFirestoreGlobalSync?.version==="v266-firestore-global-realtime-sync")return;
    const app=getApps().length?getApp():null,auth=app?getAuth(app):null,db=app?getFirestore(app):null;
    if(!auth||!db)return;
    const VERSION="v266-firestore-global-realtime-sync";
    const TZ="America/Argentina/Cordoba";
    const DEBOUNCE=120;
    const CACHE_PREFIXES=["explora_fast_cache_","explora_weekly_v","explora_closure_v","performanceRankingCache_","explora_performance_history_","explora.dashboard.notice."];
    const state={generation:0,uid:"",role:"",profileId:"",periodId:"",contextKey:"",listeners:new Map(),entities:new Map(),sourceMeta:new Map(),errors:new Map(),pending:new Set(),timer:0,revision:0,committedRevision:0,refreshing:false,queued:false,lastCommittedAt:0,lastReason:"",active:false};
    const txt=v=>String(v??"").trim();
    const session=()=>window.ExploraSession||window.ExploraAuthSession||{};
    const role=()=>txt(session().role||(document.body.classList.contains("explora-shared-admin")?"admin":"chofer")).toLowerCase()||"chofer";
    const isAdmin=r=>/admin|administrador|owner|super/.test(r);
    const period=()=>window.ExploraOperationalClock?.getActiveWeeklyPeriod?.()||window.ExploraWeeklyEngine?.getActiveWeeklyPeriod?.()||{};
    const valid=(g=state.generation)=>g===state.generation&&state.active&&txt(auth.currentUser?.uid)===state.uid;
    const mapFor=name=>{if(!state.entities.has(name))state.entities.set(name,new Map());return state.entities.get(name)};
    const detail=snap=>({fromCache:Boolean(snap?.metadata?.fromCache),pending:Boolean(snap?.metadata?.hasPendingWrites)});
    function purgeStorage(){for(const storage of [localStorage,sessionStorage]){try{const keys=[];for(let i=0;i<storage.length;i++){const k=storage.key(i);if(k&&CACHE_PREFIXES.some(p=>k.startsWith(p)))keys.push(k)}keys.forEach(k=>storage.removeItem(k))}catch(_){}}try{window.ExploraFastCache?.clearOperational?.()}catch(_){} }
    function clearPrivateState(){state.entities.clear();state.sourceMeta.clear();state.errors.clear();state.pending.clear();state.lastReason="";state.lastCommittedAt=0;try{window.ExploraWeeklyEngine?.stop?.({reset:true})}catch(_){}try{window.ExploraPerformanceEngine?.resetOperationalState?.({resetAtMs:Date.now()})}catch(_){}try{window.ExploraReceiptsController?.invalidate?.()}catch(_){}window.dispatchEvent(new CustomEvent("explora:firestore-state-cleared",{detail:{version:VERSION,generation:state.generation}}));}
    function stop({purge=true}={}){state.generation++;state.active=false;clearTimeout(state.timer);state.timer=0;for(const [,u] of state.listeners){try{u()}catch(_){}}state.listeners.clear();state.refreshing=false;state.queued=false;state.revision++;clearPrivateState();if(purge)purgeStorage();}
    function normalizeSnapshot(name,snap){const target=mapFor(name);const changes=typeof snap.docChanges==="function"?snap.docChanges():[];if(changes.length){for(const ch of changes){const id=ch.doc.id;if(ch.type==="removed")target.delete(id);else target.set(id,{id,...(ch.doc.data()||{})})}}else if(Array.isArray(snap.docs)){target.clear();for(const d of snap.docs)target.set(d.id,{id:d.id,...(d.data()||{})})}else if(typeof snap.exists==="function"){target.clear();if(snap.exists())target.set(snap.id,{id:snap.id,...(snap.data()||{})})}return target;}
    function sourceKind(name){if(/billing|cobro|servicio|factur/.test(name))return"billing";if(/gasto|expense/.test(name))return"expense";if(/deriv/.test(name))return"derivation";if(/cierre|closure/.test(name))return"closure";if(/deuda|debt/.test(name))return"debt";if(/prestamo|loan/.test(name))return"loan";if(/perfil|profile|chofer|usuario|avatar/.test(name))return"profile";if(/auto|vehic|asign/.test(name))return"vehicle";if(/ranking/.test(name))return"performance";if(/config/.test(name))return"state";return"state";}
    function invalidate(kind,reason){const ctx={uid:state.uid,role:state.role,weeklyPeriodId:state.periodId};const all=["dashboard_weekly_billing","dashboard_weekly_expenses","billing_ranking","derivation_ranking","performance_bundle","rankingSnapshot","derivationSnapshot"];const by={billing:["dashboard_weekly_billing","billing_ranking","performance_bundle","rankingSnapshot"],expense:["dashboard_weekly_expenses","performance_bundle"],derivation:["billing_ranking","derivation_ranking","performance_bundle","rankingSnapshot","derivationSnapshot"],closure:["performance_bundle"],profile:["billing_ranking","derivation_ranking","rankingSnapshot","derivationSnapshot"],performance:all,vehicle:all,debt:["performance_bundle"],loan:["performance_bundle"],state:all};for(const n of by[kind]||all)try{window.ExploraFastCache?.invalidate?.(n,ctx)}catch(_){}try{window.ExploraWeeklyEngine?.invalidate?.(reason,{refresh:false})}catch(_){}if(["billing","derivation","profile","performance","state"].includes(kind))try{window.ExploraPerformanceEngine?.invalidateRankingCache?.(reason)}catch(_){}if(["billing","expense","derivation","closure","debt","loan","state"].includes(kind))try{window.ExploraInvalidateWeeklyClosure?.(reason,{refresh:false})}catch(_){} }
    function schedule(name){state.pending.add(name);clearTimeout(state.timer);state.timer=setTimeout(commitPending,DEBOUNCE)}
    async function commitPending(){state.timer=0;if(!valid())return;const names=[...state.pending];state.pending.clear();if(!names.length)return;const g=state.generation,rev=++state.revision,reason=names.map(n=>`firestore:${n}`).join("+");for(const n of names)invalidate(sourceKind(n),reason);if(state.refreshing){state.queued=true;return}state.refreshing=true;try{const loader=window.ExploraWeeklyEngine?.getDriverWeeklyFinancialSnapshot||window.ExploraWeeklyEngine?.getDriverWeeklySnapshot;const tasks=[];if(typeof loader==="function"&&state.periodId)tasks.push(Promise.resolve(loader(state.uid,state.periodId,{force:true,allowLegacyScan:false,refreshInBackground:false,reason})));else tasks.push(Promise.resolve(null));tasks.push(Promise.resolve(window.ExploraPerformanceEngine?.refresh?.({force:true,reason})||null).catch(()=>null));const [weekly]=await Promise.all(tasks);if(!valid(g)||rev<state.revision)return;state.committedRevision=rev;state.lastCommittedAt=Date.now();state.lastReason=reason;const perf=window.ExploraPerformanceEngine?.getState?.()||{};const payload={...(weekly||{}),uid:state.uid,driverUid:state.uid,choferUid:state.uid,weeklyPeriodId:state.periodId,periodoSemanalId:state.periodId,timeZone:TZ,snapshotRevision:rev,requestId:rev,calculatedAt:new Date().toISOString(),realtime:true,realtimeCommitted:true,realtimeReason:reason,rankingRows:perf.rows||[],derivationRows:perf.derivations||[],derivationLeader:perf.currentDerivationLeader||null};window.dispatchEvent(new CustomEvent("explora:unified-weekly-snapshot",{detail:payload}));window.dispatchEvent(new CustomEvent("explora:weekly-summary",{detail:payload}));window.dispatchEvent(new CustomEvent("explora:performance-updated",{detail:{...perf,snapshotRevision:rev,weeklyPeriodId:state.periodId,realtimeCommitted:true}}));window.dispatchEvent(new CustomEvent("explora:operational-snapshot-updated",{detail:payload}));window.dispatchEvent(new CustomEvent("explora:firestore-global-state",{detail:{version:VERSION,generation:g,revision:rev,reason,periodId:state.periodId,weeklyPeriodId:state.periodId,entities:Object.fromEntries([...state.entities].map(([k,v])=>[k,[...v.values()]]))}}));try{window.ExploraFastCache?.renderWeeklySnapshot?.(payload)}catch(_){}
      }catch(error){if(valid(g)){console.error("[EXPLORA v266 realtime]",error);window.ExploraProductionPolicy?.handle?.("firestore-sync",error,{message:"No pudimos actualizar la información en tiempo real.",context:{reason,uid:state.uid,role:state.role}})}}finally{state.refreshing=false;if(state.queued&&valid(g)){state.queued=false;schedule("queued")}}}
    function listenerError(name,error,g){if(!valid(g))return;state.errors.set(name,{code:txt(error?.code),message:txt(error?.message),at:Date.now()});console.warn(`[EXPLORA v266 listener:${name}]`,error?.code||error?.message||error);window.dispatchEvent(new CustomEvent("explora:firestore-listener-error",{detail:{name,code:error?.code||"",permissionDenied:/permission-denied|unauthorized/i.test(txt(error?.code||error?.message)),generation:g}}));}
    function add(name,ref,g){if(state.listeners.has(name))return;try{const unsub=onSnapshot(ref,{includeMetadataChanges:true},snap=>{if(!valid(g))return;const m=detail(snap);state.sourceMeta.set(name,{...m,at:Date.now()});normalizeSnapshot(name,snap);if(m.pending)return;if(m.fromCache&&navigator.onLine)return;schedule(name)},error=>listenerError(name,error,g));state.listeners.set(name,unsub)}catch(error){listenerError(name,error,g)}}
    function scopedCollection(name,fields,g){for(const [suffix,field,value] of fields){if(value)add(`${name}:${suffix}`,query(collection(db,name),where(field,"==",value)),g)}}
    function build(g){const uid=state.uid,pid=state.periodId,admin=isAdmin(state.role);add("profile:usuario",doc(db,"usuarios",uid),g);if(state.profileId)add("profile:chofer-doc",doc(db,"choferes",state.profileId),g);else add("profile:chofer-uid",query(collection(db,"choferes"),where("uid","==",uid)),g);add("operational:state",doc(db,"app_operational_state","current"),g);add("weekly:own",doc(db,"acumulados_semanales",`${pid}_${uid}`),g);add("weekly:ranking",query(collection(db,"acumulados_semanales"),where("weeklyPeriodId","==",pid)),g);
      if(admin){for(const [n,f] of [["billing_records","weeklyPeriodId"],["facturaciones","weeklyPeriodId"],["cobros","weeklyPeriodId"],["servicios","weeklyPeriodId"],["gastos","weeklyPeriodId"],["derivaciones","weeklyPeriodId"],["cierres_semanales","weeklyPeriodId"],["deudas_choferes","weeklyPeriodId"],["prestamos_operativos","weeklyPeriodId"],["prestamos_explora","weeklyPeriodId"],["pagos","weeklyPeriodId"]])add(`${n}:period`,query(collection(db,n),where(f,"==",pid)),g);for(const n of ["choferes","usuarios","vehiculos","autos","asignaciones_autos","configuracion","configuraciones"])add(`${n}:admin`,collection(db,n),g)}else{scopedCollection("billing_records",[["driverUid","driverUid",uid],["choferUid","choferUid",uid],["uid","uid",uid]],g);scopedCollection("facturaciones",[["driverUid","driverUid",uid],["choferUid","choferUid",uid],["uid","uid",uid]],g);scopedCollection("cobros",[["driverUid","driverUid",uid],["choferUid","choferUid",uid],["uid","uid",uid]],g);scopedCollection("servicios",[["driverUid","driverUid",uid],["choferUid","choferUid",uid]],g);scopedCollection("gastos",[["choferUid","choferUid",uid],["driverUid","driverUid",uid],["uid","uid",uid],["ownerUid","ownerUid",uid]],g);scopedCollection("derivaciones",[["receptorUid","receptorUid",uid],["emisorUid","emisorUid",uid],["senderUid","senderUid",uid],["derivadorUid","derivadorUid",uid]],g);for(const n of ["cierres_semanales","deudas_choferes","prestamos_operativos","prestamos_explora","pagos"])scopedCollection(n,[["driverUid","driverUid",uid],["choferUid","choferUid",uid],["uid","uid",uid]],g);scopedCollection("asignaciones_autos",[["driverUid","driverUid",uid],["choferUid","choferUid",uid]],g)}
      add("profiles:public",collection(db,"choferes"),g);for(const parent of ["performance_public"]){add(`${parent}:summary`,doc(db,parent,pid),g);add(`${parent}:drivers`,collection(db,parent,pid,"drivers"),g)} }
    function start(reason="start"){const user=auth.currentUser,p=period(),r=role(),activeSession=session();if(!user?.uid||!p?.id||!activeSession?.initialized||!activeSession?.authReady||activeSession?.closing||activeSession?.authUser?.uid!==user.uid||!r){stop();return Promise.resolve(null)}const profileId=txt(activeSession.profileDocumentId||activeSession.driverId||"");const key=`${user.uid}|${r}|${p.id}|${profileId}`;if(state.active&&state.contextKey===key){schedule(reason);return Promise.resolve(null)}stop();state.uid=user.uid;state.role=r;state.profileId=profileId;state.periodId=p.id;state.contextKey=key;state.active=true;const g=state.generation;build(g);schedule(reason);return Promise.resolve(null)}
    const mutations=["explora:cobro-registrado","explora:gasto-registrado","explora:derivacion-aceptada","explora:derivacion-rechazada","explora:derivacion-completada","explora:derivacion-facturada","explora:weekly-closure","explora:closure-receipt-updated","explora:loan-requested","explora:loan-payment","explora:avatar-updated","explora:profile-updated","explora:simulation-updated","explora:app-reset","explora:app-launched"];
    mutations.forEach(n=>window.addEventListener(n,()=>schedule(`mutation:${n}`)));
    window.addEventListener("explora:session-opened",()=>start("session-opened"));window.addEventListener("explora:auth-cleared",()=>stop());window.addEventListener("explora:operational-period-changed",()=>start("period-changed"));window.addEventListener("online",()=>start("online"));window.addEventListener("pageshow",()=>start("pageshow"));document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")start("foreground")});onAuthStateChanged(auth,user=>{if(user)queueMicrotask(()=>start("auth-state"));else stop()});document.addEventListener("DOMContentLoaded",()=>setTimeout(()=>start("startup"),50));
    const api=Object.freeze({version:VERSION,start,ensure:start,refresh:(o={})=>{schedule(o.reason||"manual");return Promise.resolve(null)},stop,invalidate:(kind="state",reason="manual")=>{invalidate(kind,reason);schedule(reason)},getState:()=>({version:VERSION,generation:state.generation,uid:state.uid,role:state.role,periodId:state.periodId,contextKey:state.contextKey,listeners:state.listeners.size,listenerNames:[...state.listeners.keys()],revision:state.revision,committedRevision:state.committedRevision,lastCommittedAt:state.lastCommittedAt,lastReason:state.lastReason,errors:[...state.errors.entries()],sources:[...state.sourceMeta.entries()]})});window.ExploraFirestoreGlobalSync=api;window.ExploraOperationalSync=api;window.ExploraDashboardRealtimeCoordinator=api;window.refreshDashboardFromOperationalSnapshot=o=>api.refresh(o||{});
  })();
  