
(()=>{"use strict";if(window.ExploraSequentialValidation)return;
const visible=el=>{if(!el||el.disabled||el.hidden)return false;const s=getComputedStyle(el);if(s.display==='none'||s.visibility==='hidden')return false;return !!(el.offsetWidth||el.offsetHeight||el.getClientRects().length)};
const messageFor=el=>el.dataset.validationMessage||({email:'Ingresá un correo válido para continuar.',number:'Ingresá un monto válido para continuar.'}[el.type])||(el.type==='file'?'Subí el comprobante obligatorio para continuar.':el.tagName==='SELECT'?'Seleccioná una opción para continuar.':'Completá este campo para continuar.');
function clear(el){el.removeAttribute('aria-invalid');el.classList.remove('explora-field-error');const id=el.getAttribute('aria-describedby');if(id){const msg=document.getElementById(id);if(msg?.dataset.exploraValidation==='true')msg.remove();el.removeAttribute('aria-describedby');}}
function mark(el,text){clear(el);el.setAttribute('aria-invalid','true');el.classList.add('explora-field-error');let id=`exploraValidation_${el.id||Math.random().toString(36).slice(2)}`;let msg=document.getElementById(id);if(!msg){msg=document.createElement('div');msg.id=id;msg.dataset.exploraValidation='true';msg.className='billing-message is-error';el.insertAdjacentElement('afterend',msg);}msg.textContent=text;el.setAttribute('aria-describedby',id);}
function firstInvalid(root){for(const el of root.querySelectorAll('input[required],select[required],textarea[required],[data-required="true"]')){if(!visible(el))continue;let ok=true;if(el.matches('input,select,textarea'))ok=el.checkValidity()&&String(el.value||'').trim()!=='';else ok=el.getAttribute('aria-checked')==='true'||el.dataset.value; if(!ok)return el;}return null;}
function reveal(el){for(let p=el.parentElement;p&&p!==document.body;p=p.parentElement){if(p.hidden)p.hidden=false;if(p.tagName==='DETAILS')p.open=true;const panel=p.closest?.('[data-derivation-panel]');if(panel&&!panel.classList.contains('is-active')){const key=panel.dataset.derivationPanel;document.querySelector(`[data-derivation-tab="${key}"]`)?.click();}}}
function validate(root){const el=firstInvalid(root);if(!el)return true;reveal(el);mark(el,messageFor(el));const container=el.closest('.billing-modal-content,.weekly-closure-content,.derivation-modal,[data-scroll-container]')||window.ExploraNearestScrollable?.(el);if(container)window.ExploraScrollElementInside?.(container,el,{top:18,bottom:30});requestAnimationFrame(()=>el.focus?.({preventScroll:true}));return false;}
document.addEventListener('input',e=>{if(e.target?.matches?.('input,select,textarea,[data-required="true"]'))clear(e.target)});document.addEventListener('change',e=>{if(e.target?.matches?.('input,select,textarea,[data-required="true"]'))clear(e.target)});
document.addEventListener('submit',e=>{if(!validate(e.target)){e.preventDefault();e.stopImmediatePropagation();}},true);
window.ExploraSequentialValidation={validate,clear,firstInvalid};})();
